# Generated by Django 4.2.3 on 2023-08-24 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0003_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('checkout_condition', models.CharField(max_length=100)),
                ('return_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_services.company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_services.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_services.employee')),
            ],
        ),
    ]
